version: '3.9'

services:
  nginx:
    build:
      context: docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./:/app:ro
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker
      dockerfile: development/php-fpm/Dockerfile
    environment:
      DATABASE_URL: postgresql://app:secret@postgres:5432/app?serverVersion=13&charset=utf8
      PHP_IDE_CONFIG: serverName=ProjectName
    volumes:
      - ./:/app
    depends_on:
      - postgres

  php-cli:
    build:
      context: docker
      dockerfile: development/php-cli/Dockerfile
    environment:
      DATABASE_URL: postgresql://app:secret@postgres:5432/app?serverVersion=13&charset=utf8
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

volumes:
  postgres:
