version: '3.9'

services:

  app:
    build:
      context: ./images/php-fpm
      args:
        - USER_ID
        - GROUP_ID
    container_name: app
    volumes:
      - ./www:/var/www

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www:ro
      - ./logs:/var/log/nginx
    ports:
    - "8080:80"
    depends_on:
      - app
